### ISSUE TITLE
Injecting CqlSession into Repository class dependency can't be resolved error

### ISSUE THREAD

**Issue by classifieds-dev** [micronaut-projects/micronaut-cassandra#13]
Hello,

I'm new to micronaut but not to programming. Anyway, I was originally trying to use AWSs new MCS (managed cassandra service) service with C#. However, I have ran into several issues and limitations at the moment with C# MCS. That has lead me here. I decided it would be best to create a separate private api gateway using java to act as a middle man between my c# public api and cassandra given MCS has more support for java than anything else at the moment.  That being said my Java is a but rusty through I'm very familiar with most the patterns used in micronaut having spent a day with it. 

My current problem is that I can't seem to inject the CqlSession into my repository. I'm always getting an error that the service dependency can not be found. Looking at the code though it appears that the service should be generated via the factory. If someone would take a quick look at my code and tell me what I'm doing wrong I would appreciate it.

https://bitbucket.org/oddz/classifieds-cass-api/src/master/

**Comment by pollend** [comment]
do you have any logs with you trying to run this on AWS. just want to see if the CQLsession is created.   

I have a working example project for cassandra you can look at if your still have problems: https://github.com/pollend/micronaut-cassandra-sample/blob/master/src/main/resources/application.yml

**Comment by ilopmar** [comment]
Driver version has been updated to 4.8.0. @pollend can we close this, right?

**Comment by pollend** [comment]
I think this could be closed.
