### ISSUE TITLE
Mismatch with 1.2.0

### ISSUE THREAD

**Issue by knoma** [micronaut-projects/micronaut-cassandra#16]
I'm using the 1.2.0 of the Cassandra config and it's loading cassandra-driver-core-3.1.0 and not 4.4 as mentioned in the docs.

https://github.com/micronaut-projects/micronaut-cassandra/blob/master/src/main/docs/guide/setup.adoc

I'm getting the cluster and not aCqlSession , it would be better to have a session rather the cluster.

```
        Cluster cluster = applicationContext.getBean(Cluster.class);
        Session session = cluster.connect();
```

**Comment by ilopmar** [comment]
Only master branch uses the 4.x version of `cassandra-driver-core`: https://github.com/micronaut-projects/micronaut-cassandra/blob/master/cassandra/build.gradle#L7. 
Update to `micronaut-cassandra` `2.0.0`
