### ISSUE TITLE
Potential resource leak identified within datastax cassandra driver versions <= 4.11.1

### ISSUE THREAD

**Issue by aozmen121** [micronaut-projects/micronaut-cassandra#248]
### Feature description

There is currently a potential resource leak when attempting todo batch insert against Cassandra db with  datastax-cassandra-driver-version 4.11.1  see data stack Jira board: 
- https://datastax-oss.atlassian.net/browse/JAVA-2947
- https://datastax-oss.atlassian.net/browse/JAVA-3004

This leak was reproducible using micronaut-cassandra version 4.0.0, which is pulling down dependency version 4.11.1 of datastax-cassandra-driver.

The fix for the resource leak is available for datastax-cassandra-driver from  >= 4.11.2 versions onwards.

Recommended to use latest version of datastax-cassandra-driver: [4.14.1](https://github.com/datastax/java-driver/releases/tag/4.14.1)

**Comment by sdelamo** [comment]
Resolved via https://github.com/micronaut-projects/micronaut-cassandra/pull/249
