### ISSUE TITLE
Potential resource leak identified within datastax cassandra driver versions <= 4.11.1

### ISSUE THREAD

**Issue by aozmen121** [micronaut-projects/micronaut-cassandra#250]
### Expected Behavior

Should not cause resource leakage when batch inserting into Cassandra db. 

### Actual Behaviour

There is currently a potential resource leak when attempting todo batch inserts against Cassandra db with datastax-cassandra-driver-version 4.11.1

```
2022-06-22T14:22:16,798 [s0-io-1] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
    io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:402)
    io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
    io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
    io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:140)
    io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:120)
    io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:150)
    io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
    io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
    io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
    io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
    io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
    io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    java.base/java.lang.Thread.run(Thread.java:829)
```

### Steps To Reproduce

Batch insert into Cassandra DB.

### Environment Information

Operating System: Linux
micronaut-cassandra Version: 4.0.0
JDK Version: 11

There is currently a potential resource leak when attempting todo batch insert against Cassandra db with datastax-cassandra-driver-version 4.11.1 see data stack Jira board:

- https://datastax-oss.atlassian.net/browse/JAVA-2947
- https://datastax-oss.atlassian.net/browse/JAVA-3004

This leak was reproducible using micronaut-cassandra version 4.0.0, which is pulling down dependency version 4.11.1 of datastax-cassandra-driver.

The fix for the resource leak is available for datastax-cassandra-driver from >= 4.11.2 versions onwards.

Recommended to use latest version of datastax-cassandra-driver: [4.14.1](https://github.com/datastax/java-driver/releases/tag/4.14.1)

### Example Application

https://datastax-oss.atlassian.net/browse/JAVA-2947

### Version

4.0.0

**Comment by sdelamo** [comment]
Resolved via https://github.com/micronaut-projects/micronaut-cassandra/pull/249
