### ISSUE TITLE
GMavenPlus Maven Compile Error

### ISSUE THREAD

**Issue by brianwyka** [micronaut-projects/micronaut-cassandra#42]
## Description

Sine Micronaut `2.0.0` has a groovy upgrade to `3.0.3`, there seems to be an incompatibility with this library's transitive dependencies.

Here is the relevant part of the dependency tree output:

```txt
[INFO] +- io.micronaut.cassandra:micronaut-cassandra:jar:2.0.0:compile
[INFO] |  +- com.datastax.oss:java-driver-core:jar:4.6.1:compile
[INFO] |  |  \- org.apache.tinkerpop:gremlin-driver:jar:3.4.5:compile
[INFO] |  |     +- org.codehaus.groovy:groovy:jar:indy:2.5.7:compile
[INFO] |  |     \- org.codehaus.groovy:groovy-json:jar:indy:2.5.7:compile
```

And link to reference in mvn repository: 
https://mvnrepository.com/artifact/org.apache.tinkerpop/gremlin-driver/3.4.5

### Workaround
The following exclusions allow me to compile and run tests successfully.

```xml
<dependency>
    <groupId>io.micronaut.cassandra</groupId>
    <artifactId>micronaut-cassandra</artifactId>
    <version>2.0.0</version>
    <exclusions>
        <exclusion>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-json</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

### Task List

- [ ] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Expected Behaviour

Build should succeed without groovy errors...

### Actual Behaviour

Build fails with groovy incompatibility message:

```
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.9.0:compileTests (default) on project micronaut-edge-test-pom: Error occurred while calling a method on a Groovy class from classpath.: InvocationTargetException: Class org.codehaus.groovy.ast.ModuleNode does not implement the requested interface org.codehaus.groovy.ast.NodeMetaDataHandler -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.9.0:compileTests (default) on project micronaut-edge-test-pom: Error occurred while calling a method on a Groovy class from classpath.
```

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** `2.0.0`
- **JDK Version:** `1.8`

**Comment by ctoestreich** [comment]
We have raised this up before.  I think we need to put an enforcer test into a simple maven project that uses the bom/pom and all the libs so that the team knows when these conflicts are created.  @brianwyka Rock Paper Scissors?

**Comment by brianwyka** [comment]
✂️

**Comment by ctoestreich** [comment]
⛰️

**Comment by wetted** [comment]
@brianwyka @ctoestreich 

Micronaut 3 and Micronaut 4 use versions of `com.datastax.oss:java-driver-core` that no longer include groovy transitively. 

If this is still a problem for you feel free to re-open this issue with an example that demonstrates the failure.
